paul_maxwell_guestbook_homepage:
    pattern:  /
    defaults: { _controller: PaulMaxwellGuestbookBundle:Default:index }

paul_maxwell_guestbook_remove:
    pattern: /{page}/remove/{id}
    defaults: { _controller: PaulMaxwellGuestbookBundle:Default:remove }
    requirements:
        page: "^[0-9]+$"
